version: "3.0"

services:
  redis_backend:
    image: redis:5
    ports:
      - 6379:6379
    networks:
      - nginx_network
  server:
    depends_on:
      - redis_backend
    image: task-director-server:latest
    networks:
      - nginx_network
  controller:
    depends_on:
      - redis_backend
    image: task-director-controller:latest
    networks:
      - nginx_network
  nginx:
    depends_on:
      - server
      - controller
    image: nginx:1.19.0-alpine
    ports:
      - 1300:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
