version: "3.0"

services:
  redis_backend:
    image: redis:5
    ports:
      - 6379:6379

  server:
    depends_on:
      - redis_backend
    image: ghcr.io/alexander-scott/task-sharding/server:latest

  controller:
    depends_on:
      - redis_backend
    image: ghcr.io/alexander-scott/task-sharding/controller:latest

  nginx:
    depends_on:
      - server
      - controller
    image: nginx:1.19.0-alpine
    ports:
      - 1300:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

