name: Docker Image CI

on: [push]

jobs:
  docker_lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Hadolint Action
      uses: hadolint/hadolint-action@v1.6.0
      with:
        dockerfile: server/Dockerfile

  docker_build:
    needs: [docker_lint, pylint, unit_tests, coverage, integration]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.WRITE_PACKAGES_TOKEN }}

    - name: Build and push the server docker image
      uses: docker/build-push-action@v2
      with:
        context: ./server
        target: server
        push: true
        tags: |
          ghcr.io/alexander-scott/task-sharding/server:latest

    - name: Build and push the controller docker image
      uses: docker/build-push-action@v2
      with:
        context: ./server
        target: controller
        push: true
        tags: |
          ghcr.io/alexander-scott/task-sharding/controller:latest

