name: Docker Image CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Hadolint Action
      uses: hadolint/hadolint-action@v1.6.0
  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the server Docker image
      run: docker build --file server/Dockerfile --target server --tag task-director-server:$(date +%s) .
    - name: Build the controller Docker image
      run: docker build --file server/Dockerfile --target controller --tag task-director-controller:$(date +%s) .
